### ISSUE TITLE
Page (state?) moves down when clicking

### ISSUE THREAD

**Issue by edinchez** [homerjam/angular-gsapify-router#15]
Forgive me for improper wording, I'm a beginner at Angular. I've been having this weird bug where when I click on a page/link, the content of the current page moves down a bit before the next one comes in.

I found a weird "semi-fix" by adding "position: absolute;" to the element that's being routed(?). Not sure how to call it. But it's not really how I want to use it, so it's not a fix for me. [Here's a video showing the problem and the "fix."](https://dl.dropboxusercontent.com/u/8079625/ShareX/2015/09/2015-09-24_11-15-33.mp4)

**Comment by edinchez** [comment]
One more thing I noticed is that the content of the current state moves down based on the size of the content of the next state. So I guess it must be something related to the next state? Content loads before it needs to? I have no idea.

**Comment by homerjam** [comment]
If you look at the inspector you can see that whats happening is the incoming view is added to the dom, then the transitions are applied then the outgoing view is removed. So while the transitions are occurring there are two sibling nodes (elements) within a parent node. As such, depending on the css, one nodes position maybe be influenced by the other. As you can see in the example absolute positioning is used. This module tries to be unopinionated and leave the css to the developer rather than take care of itself.

**Comment by edinchez** [comment]
I see. Is there any way I can make the incoming view to be added to the dom after the outgoing one is completely removed from the dom? I feel like that would be the only sensible resolution without murdering my CSS with absolute/fixed positions. Or do you maybe have a better idea?

**Comment by homerjam** [comment]
No you can't do this without hacking ui-router I don't think. You could try adding a delay to the incoming transition so that it begins after the outgoing transition has ended and then add this to your css:

```
.gsapify-router-in-setup {
    display: none;
}

**Comment by edinchez** [comment]
Simply adding that CSS rule fixed it! Thank you so so much!

**Comment by homerjam** [comment]
Great! Good luck with the project
