### ISSUE TITLE
Where can I see a list of the animation names that this comes with?

### ISSUE THREAD

**Issue by feniixx** [homerjam/angular-gsapify-router#19]

**Comment by homerjam** [comment]
They begin [here](https://github.com/homerjam/angular-gsapify-router/blob/master/angular-gsapify-router.js#L24)

**Comment by feniixx** [comment]
Is this better than (angular-ui-router-anim-in-out)[https://github.com/homerjam/angular-ui-router-anim-in-out]?, Will it be supported for long time?, Is it constantly developed or just a one time development project?

**Comment by homerjam** [comment]
Its an alternative to that plugin, this is one is more recent.

The key difference is that this plugin is way more configurable - for example you can use functions to define transitions and set a priority to vary transition depending on to/from state. It also has more events to hook up to.

Additionally it uses JS rather than CSS for the transitions which means you can more easily create complex transitions of multiple properties.

I use it in virtually all my projects so its well maintained. It should always work with angular 1.x and ui-router as these projects have both reached maturity and are unlikely to change.

**Comment by feniixx** [comment]
I see, isn't it available through bower?

**Comment by feniixx** [comment]
How do I add TweenMax?

**Comment by homerjam** [comment]
Yep bower too, but npm seems better setup for build tools out of the box. Each to their own of course ; )

**Comment by feniixx** [comment]
Ok, I'll move to npm, but I don't know how to load npm modules in the client `index.html` right now...

**Comment by homerjam** [comment]
it depends on your project as a whole for how you include tweenmax but the example shows one way of doing it

**Comment by homerjam** [comment]
you can just use a script tag if not using a build tool

**Comment by feniixx** [comment]
Hmmm, any tutorial link?, what build tool would you recommend?

**Comment by homerjam** [comment]
I think the demo is linked in the description, or else you can look at the example folder of the repo.

**Comment by homerjam** [comment]
I'd recommend learning the fundamentals first. Get to grips with gulp then try webpack
